### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#10]
I have seen that [no loop is used around a call](https://github.com/Shardcached/libshardcache/blob/dc0fffe246c246ac1b27f644731a4cb561f0c0b4/src/kepaxos.c#L403 "Check kepaxos_run_command()") of the function "[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "wait on a condition")".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7 "Discussion about handling of spurious wakeups")"?

**Comment by xant** [comment]
ef31536cb5aa4751a5b15940271aafc59661919b

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Shardcached/libshardcache/commit/ef31536cb5aa4751a5b15940271aafc59661919b "Addition of a predicate check").
