### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#11]
I find that include guards like "[`ARC_H`](https://github.com/Shardcached/libshardcache/blob/7635e6843869c4e1f0755e3fb021b96d0237e29c/src/arc.h#L8)" and "[`MESSAGING_H`](https://github.com/Shardcached/libshardcache/blob/7635e6843869c4e1f0755e3fb021b96d0237e29c/src/messaging.h#L1)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by xant** [comment]
df01c52344324b3de603fd5dded3c21c4849e2c8

**Comment by elfring** [comment]
Are there [any more update candidates](https://github.com/Shardcached/libshardcache/blob/7635e6843869c4e1f0755e3fb021b96d0237e29c/src/serving.h#L1 "Reconsider name selection?") left over where a similar change would help for safer API reuse?
