### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#6]
I suggest to reuse a higher level build system than [your current make file](https://github.com/Shardcached/libshardcache/blob/2b80330ff8b31630178cd4bff8e5112190510bae/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by xant** [comment]
closing this because it's not going to happen anytime soon
