### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#7]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [kepaxos_recover](https://github.com/Shardcached/libshardcache/blob/dc0fffe246c246ac1b27f644731a4cb561f0c0b4/src/shardcache_replica.c#L203)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [shardcache_node_create_from_string](https://github.com/Shardcached/libshardcache/blob/6ac9ed60d448dfc69bf5c7a96a2e24a8d0ba23b1/src/shardcache_node.c#L41)

**Comment by xant** [comment]
as commented already , no

**Comment by elfring** [comment]
I would prefer that strict error detection will become less optional in important software.
Is [the importance of software robustness](https://en.wikipedia.org/w/index.php?title=Robustness_%28computer_science%29 "Making software more robust?") increasing for this library?

**Comment by xant** [comment]
yes, but the changes you suggest here are wothless and bring no more robustness. 
btw ... do somebody pay you per comment on github issues?
