### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#8]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [destroy_volatile](https://github.com/Shardcached/libshardcache/blob/2b80330ff8b31630178cd4bff8e5112190510bae/src/shardcache.c#L294)
* [kepaxos_command_free](https://github.com/Shardcached/libshardcache/blob/dc0fffe246c246ac1b27f644731a4cb561f0c0b4/src/kepaxos.c#L106)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") to find more update candidates?
```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by xant** [comment]
9901bad1b65ea198c992ab15fed3a3815ee47188

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Shardcached/libshardcache/commit/9901bad1b65ea198c992ab15fed3a3815ee47188 "Deletion of unnecessary null pointer checks").
