### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#9]
Would you like to [replace any double quotes](https://github.com/Shardcached/libshardcache/blob/2b80330ff8b31630178cd4bff8e5112190510bae/src/shardcache.c#L17 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by xant** [comment]
using double quotes ensure including the header from the sourcedir and not the one eventually available in other include directories because installed from a previous version of the library

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by xant** [comment]
I think it's correct as it is now.
I'm not planning building and using this library anywhere else than on unix and using compilers/implementations where the double quotes mean that the file is first searched in the same directory of the file including it , otherwise looking in the directories mentions in the include path.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by xant** [comment]
true, but as I said I don't think ot's relevant for us and no changes are necessary at this stage
